---
- name: Disable Suspend on Lid Close
  lineinfile:
    path: /etc/systemd/logind.conf
    line: HandleLidSwitch=ignore
    regexp: "^#?HandleLidSwitch"
  become: True

- name: Prevent Stupid Immediate Wakeup From Suspend
  copy:
    src: rc.local
    dest: /etc/rc.d/rc.local
    mode: 0755
  become: True

- name: Misc Packages
  package:
    name: "{{ item }}"
    state: latest
  become: True
  with_items:

    - android-tools
    - bluez-tools
    - inkscape
    - pwgen
