---
- name: verify i3 directory present
  file:
    path: "{{ user.home }}/.i3"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0700
  become: True

- name: i3 config
  template:
    src: "{{ ansible_hostname }}.j2"
    dest: "{{ user.home }}/.i3/config"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0600
  become: True
