---
- name: Ensure Local Source Dir
  file:
    path: /usr/local/src
    state: directory
  become: True

- name: Clone SemiAutoKey Repository
  git:
    repo: https://github.com/dechandler/semiautokey.git
    dest: /usr/local/src/semiautokey
  become: True

- name: Auto Update Script
  copy:
    dest: /etc/cron.weekly/sak-update.sh
    content: |
      #!/bin/bash
      cd /usr/local/src/semiautokey
      git pull
    mode: 0755
  become: True
