---
- name: i3 | py3status | volume | Package Dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - alsa-utils
    - pavucontrol
  become: True

- name: i3 | py3status | volume | Copy Script
  copy:
    src: vol.py
    dest: /usr/local/libexec/py3status/vol.py
    mode: 0755
  become: True