---
- name: Terminator | Ensure Config Directory
  file:
    path: "{{ user.home }}/.config/terminator"
    state: directory
    mode: 0700
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  become: True

- name: Terminator | Config
  copy:
    src: "config"
    dest: "{{ user.home }}/.config/terminator/config"
    mode: 0600
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  become: True