---
# Nyx (Lenovo X1 Carbon, 5th Gen)

- name: Nyx | Standard Configuration
  hosts: nyx

  tasks:

    - include_role:
        name: base/openssh
    - include_role:
        name: shell/zsh
    - include_role:
        name: shell/utils