---
- name: SSH Client | {{ user.name }} | Ensure Directories
  file:
    path: "{{ user.home }}/.ssh/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0700
  with_items:
    - public
    - private
    - sockets
  become: True

- name: SSH Client | {{ user.name }} | Ensure SSHable
  user:
    name: "{{ user.name }}"
    groups:
      - ssh
    append: True
  become: True
  when: "'authorized_keys' in user"
 
- name: SSH Client | {{ user.name }} | Authorized Keys
  authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ ssh_keys[item].pub }}"
    exclusive: True
  with_items: "{{ user.authorized_keys }}"
  become: True

- name: SSH Client | {{ user.name }} | Copy SSH Private Keys
  copy:
    content: "{{ ssh_keys[item].key }}"
    dest: "{{ user.home }}/.ssh/private/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0600
  with_items: "{{ user.ssh_private_keys }}"
  become: True
  when: "'ssh_private_keys' in user"

- name: SSH Client | {{ user.name }} | Copy Corresponding SSH Public Keys
  copy:
    content: "{{ ssh_keys[item].pub }}"
    dest: "{{ user.home }}/.ssh/public/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0600
  with_items: "{{ user.ssh_private_keys }}"
  become: True
  when: "'ssh_private_keys' in user"

- name: SSH Client | {{ user.name }} | Config
  template:
    src: "private/ssh-client-config.j2"
    dest: "{{ user.home }}/.ssh/config"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0600
  become: True
