---
- name: Determine if Docker Installed
  stat:
    path: /usr/bin/docker
  register: docker_installed

- block:
    - name: Download Docker Install Script
      get_url:
        url: https://raw.githubusercontent.com/docker/docker-install/master/install.sh
        dest: /dev/shm/docker-install.sh
        mode: 0700
      become: True

    - name: Run Docker Install
      command: /dev/shm/docker-install.sh
      become: True
  when: not docker_installed.stat.exists

- name: Start and Enable Docker Service
  service:
    name: docker
    state: started
    enabled: True

- name: Install systemd-docker
  package:
    name: systemd-docker
    state: latest
  become: True

- name: Install Docker Python Modules
  package:
    name: "{{ item }}"
    state: latest
  become: True
  with_items:
    - python-docker
    - python3-docker