---
- name: Sublime | Ensure Directories Used in Role
  file:
    path: "{{ user.home }}/.config/sublime-text-3/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0700
  with_items:
    - Local
    - Packages/User
  become: True

- name: Sublime | Copy User Config
  copy:
    dest: "{{ user.home }}/.config/sublime-text-3/Packages/User/Preferences.sublime-settings"
    src: Preferences.sublime-settings
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0600
  become: True

- name: Sublime | Copy License Key
  copy:
    dest: "{{ user.home }}/.config/sublime-text-3/Local/License.sublime_license"
    content: "{{ sublime_key }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0600
  become: True