---
- name: Get Current and Latest Raspbian Lite Versions
  set_fact:
    current_raspbian_version: "{{ lookup('file', role_path + '/files/version') }}"
    latest_raspbian_version: "{{ lookup('raspbian_version', 'latest') }}"

- debug: var=current_raspbian_version
- debug: var=latest_raspbian_version

- name: Ensure Latest Image
  delegate_to: localhost
  block:
    - name: Download and Extract Image
      unarchive:
        src: "https://downloads.raspberrypi.org/raspbian_lite_latest"
        dest: /dev/shm
        remote_src: True
        list_files: True
      register: list_files

    - name: Move Image into Files
      command: mv -f /dev/shm/{{ list_files.files.0 }} {{ raspbian_img }}

    - name: Update Current Version
      copy:
        dest: "{{ role_path }}/files/version"
        content: "{{ latest_raspbian_version }}"

  when: latest_raspbian_version > current_raspbian_version


- name: Get Image File Offsets
  set_fact:
    offsets: "{{ lookup('img_mount_offset', raspbian_img) }}"

- debug: var=offsets

- name: Install First-Run Script
  delegate_to: localhost
  block:
    - name: Create Temporary Mountpoint
      file:
        path: "{{ tmp_mount }}"
        state: directory

    - debug: var=raspbian_img

    - name: Mount Image Root
      command: mount -o loop,offset={{ offsets.1 }} {{ raspbian_img }} {{ tmp_mount }}

    - name: Install First-Run Script
      template:
        src: rc.local
        dest: "{{ tmp_mount }}/etc/rc.local"
        mode: 0755

  always:
    - name: Unmount Image Root
      mount:
        path: "{{ tmp_mount }}"
        state: unmounted

    - name: Clean Up Temp Mount Dir
      file:
        path: "{{ tmp_mount }}"
        state: absent

  become: True
