---
- set_fact:
    static_isolated_hosts: >-
        {
          {% for net in networks.values() %}
              {% set net_loop = loop %}
              {% for host_info in net.hosts|default([]) %}
                  {% set cidr = net.cidr | ipsubnet(30, loop.index) %}
                  "{{ host_info.name }}": {
                      "isolation_subnet_cidr": "{{ cidr }}",
                      "gateway": "{{ cidr | ipmath(1) }}",
                      "ip": "{{ cidr | ipmath(2) }}",
                      "hwaddr": "{{ host_info.hwaddr }}"
                  }{% if not (net_loop.last and loop.last) %},{% endif %}
              {% endfor %}
          {% endfor %}
        }

- set_fact:
    target_ips: >-
        {
          {% for name, info in static_isolated_hosts.items() %}
              "{{ name }}": "{{ info.ip }}",
          {% endfor %}
          {% for net_name, net_info in networks.items() %}
              "{{ net_name }}": "{{ net_info.cidr }}"{% if not loop.last %},{% endif %}
          {% endfor %}
        }
