---
- include_tasks: common.yml
  vars:
    role: router
    files:
      - setup.sh
      - network-interfaces
      - iptables
      - dns-rules.sh
      - dns-rules.conf
      - dnsmasq.conf
    executable_files:
      - setup.sh
      - dns-rules.sh
