---
- include_tasks: common.yml
  vars:
    role: sshd-login
    files:
      - setup.sh
      - sshd_config
    executable_files:
      - setup.sh


- name: Login Authorized Keys
  delegate_to: localhost
  template:
    src: authorized_keys
    dest: "{{ local_build_dir }}/sshd-login/authorized_keys"
  vars:
    user: "{{ login_user }}"
