---
- name: Pull Docker Image
  docker_image:
    name: ryansch/unifi-rpi:latest
  become: True

- name: Copy Systemd Unit File
  copy:
    src: unifi.service
    dest: /etc/systemd/system/unifi.service
  become: True
