---
- name: SSHD | Config File
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -t -f %s
  become: True
  notify: ['sshd restart']

- name: SSHD | Ensure SSHable Group
  group:
    name: ssh
  become: True