---
- name: Ubuntu Fonts | Test if Installed
  stat:
    path: /usr/share/fonts/ubuntu-font-family-0.83
  register: ubuntu_fonts_installed

- name: Ubuntu Fonts | Download and Install
  unarchive:
    src: https://assets.ubuntu.com/v1/fad7939b-ubuntu-font-family-0.83.zip
    dest: /usr/share/fonts/
    remote_src: True
  become: True
  when: not ubuntu_fonts_installed.stat.exists
