---
- include_role:
    name: "i3-desktop/{{ role }}"
  loop_control:
    loop_var: role
  with_items:
    - i3
    - py3status
    - xrandr
    - terminator
    - j4-dmenu-desktop
    - xbindkeys
    - rofi

- name: Disable Suspend on Lid Close
  lineinfile:
    path: /etc/systemd/logind.conf
    line: HandleLidSwitch=ignore
    regexp: "^#?HandleLidSwitch"
  become: True