---
# Chronos (Raspberry Pi 3)

- name: Chonos | Standard Configuration
  hosts: chronos
  tasks:
    - apt:
        update_cache: True
        upgrade: True
      become: True

    - include_role:
        name: base/openssh
    - include_role:
        name: shell/zsh
    - include_role:
        name: shell/utils
    - include_role:
        name: raspi/docker
    - include_role:
        name: raspi/unifi-controller

    - include_role:
        name: base/user
      vars:
        user: "{{ primary_user }}"