---
# Nyx (Lenovo X1 Carbon, 5th Gen)


- name: Nyx | Standard Configuration
  hosts: nyx

  tasks:

    - include_role:
        name: service/sshd

    #- include_role:
    #    name: shell/zsh
    #- include_role:
    #    name: shell/utils
    #- include_role:
    #    name: shell/password-store


    - include_role:
        name: desktop/setup

    - include_role:
        name: desktop/user
      vars:
        user: "{{ primary_user }}"
