---
- name: Configure Raspbian Image
  hosts: localhost
  vars:
    do_img_config: True
  tasks:
    - name: Download and Configure Raspbian Lite Image
      include_role:
        name: init/raspbian
        tasks_from: img_config
      when: do_img_config

    - name: Copy Raspbian Lite Image to microSD card
      include_role:
        name: init/raspbian
        tasks_from: flash