---
- name: Requisites
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - cups-libs.i686
    - cups-filters-libs.i686
  become: True

- name: Download and Install Xerox 6000 Driver Idempotently
  block:
    - name:
      dnf:
        name: Xerox-Phaser_6000_6010
        state: present

  rescue:
    - name: Download Xerox 6000 Driver
      unarchive:
        src: http://download.support.xerox.com/pub/drivers/6000/drivers/linux/en_GB/6000_6010_rpm_1.01_20110222.zip
        dest: /dev/shm
        remote_src: True

    - name: Install Xerox 6000 Driver
      dnf:
        name: /dev/shm/rpm_1.01_20110222/Xerox-Phaser_6000_6010-1.0-1.i686.rpm
        state: present
  become: True
