---
- name: Sublime Text | Add APT Repo (Ubuntu)
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    filename: sublime-text
  become: True
  when: ansible_distribution == "Ubuntu"
 
- name: Sublime Text | Add RPM Repo (Fedora)
  yum_repository:
    name: sublime-text
    description: Sublime Text - x86_64 - Stable
    baseurl: https://download.sublimetext.com/rpm/stable/x86_64
    gpgcheck: yes
    gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
  become: True
  when: ansible_distribution == "Fedora"

- name: Sublime Text | Install
  package:
    name: sublime-text
    state: present
  become: True
