---
- name: User | {{ user.name }} | Create
  user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    comment: "{{ user.comment }}"
    state: present
    password: "{{ pass_hashes[user.name] }}"
    home: "{{ user.home }}"
    uid: "{{ user.uid }}"
  when: "'uid' in user.keys()"
  become: True


- include_role:
    name: base/openssh
    tasks_from: user-config.yml


- name: User | {{ user.name }} | Admin User Role
  user:
    name: "{{ user.name }}"
    groups: "{{ admin_group[ansible_distribution] }}"
    append: True
  become: True
  when: "'admin' in user.roles"

- include_tasks: desktop.yml
  when: "'desktop' in user.roles"

- include_role:
    name: shell/zsh
    tasks_from: user-config.yml
  when: user.shell == "/usr/bin/zsh"

- include_role:
    name: shell/gpg
    tasks_from: user-config.yml
  when: "'gpg_keys' in user"
