---
- set_fact:
    default_user_data:
      shell: /bin/bash
      comment: ''
      home: "/home/{{ this_user.name }}"
      authorized_keys: []
      ssh_private_keys: [] 

- set_fact:
    user: "{{ default_user_data | combine(this_user) }}"

- debug:
    var: default_user_data
- debug:
    var: user

- name: User | {{ user.name }} | Create
  user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    comment: "{{ user.comment }}"
    state: present
    password: "{{ pass_hashes[user.name] }}"
    home: "{{ user.home }}"
  when: "'uid' not in user.keys()"
  become: True

- name: User | {{ user.name }} | Create (UID Specified)
  user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    comment: "{{ user.comment }}"
    state: present
    password: "{{ pass_hashes[user.name] }}"
    home: "{{ user.home }}"
    uid: "{{ user.uid }}"
  when: "'uid' in user.keys()"
  become: True


- include_role:
    name: base/openssh
    tasks_from: user-config.yml


- name: User | {{ user.name }} | Admin User Role
  user:
    name: "{{ user.name }}"
    groups: "{{ 'sudo' if ansible_distribution == 'Ubuntu' else 'wheel' }}"
    append: True
  become: True
  when: "'admin' in user.roles"

- include_tasks: desktop.yml
  when: "'desktop' in user.roles"

- include_role:
    name: shell/zsh
    tasks_from: user-config.yml
  when: user.shell == "/usr/bin/zsh"
