---
- include_tasks: teardown.yml

- name: Create Linode Instance
  delegate_to: localhost
  community.general.linode_v4:
    label: "{{ inventory_hostname }}"
    type: "{{ linode_type }}"
    region: "{{ linode_region }}"
    image: "{{ linode_image }}"
    state: present
    authorized_keys:
      - "{{ ssh_keys.automation.pub }}"
    #root_pass: "{{ init_root_pass }}"
    access_token: "{{ linode_creds.token }}"
  register: linode_out

- set_fact:
    ansible_host: "{{ linode_out.instance.ipv4.0 }}"
    ansible_user: root
    ansible_pass: "{{ linode_out.instance.root_pass }}"


- name: Create or Update DNS Record
  delegate_to: localhost
  dechandler.linode.domain_record:
    name: "{{ inventory_hostname }}"
    domain: "{{ domain }}"
    target: "{{ ansible_host }}"
    ttl: 100
    access_token: "{{ linode_creds.token }}"


- delegate_to: localhost
  wait_for:
    host: "{{ ansible_host }}"
    port: 22
