---
- name: Delete Linode Instance
  delegate_to: localhost
  community.general.linode_v4:
    label: "{{ inventory_hostname }}"
    type: "{{ linode_type }}"
    region: "{{ linode_region }}"
    image: "{{ linode_image }}"
    state: absent
    #root_pass: "{{ init_root_pass }}"
    access_token: "{{ linode_creds.token }}"
