---
- name: OpenSSH | Ensure SSHD Installed
  package:
    name: "{{ sshd_package[ansible_facts.os_family] }}"
    state: present
  become: True

- name: OpenSSH | Ensure SSHD Start on Boot
  service:
    name: "{{ sshd_service[ansible_facts.os_family] }}"
    enabled: "{{ sshd_enabled }}"
  become: True

- name: OpenSSH | Create /run/sshd
  file:
    state: directory
    path: /run/sshd
  become: True