---
- name: OpenSSH | Jump Server | {{ jump_user.name }} | Ensure User
  user:
    name: "{{ jump_user.name }}"
    group: jump
    shell: /bin/true
    home: /dev/null
  become: True

- name: OpenSSH | Jump Server | {{ jump_user.name }} | Authorized Keys
  authorized_key:
    user: "{{ jump_user.name }}"
    path: /etc/ssh/{{ jump_user.name }}.authorized_keys
    state: present
    key: "{{ ssh_keys[item].pub }}"
    exclusive: True
  with_items: "{{ jump_user.authorized_keys }}"
  become: True

- name: OpenSSH | Jump Server | {{ jump_user.name }} | Authorized Keys Permissions
  file:
    path: /etc/ssh/{{ jump_user.name }}.authorized_keys
    mode: 0640
    owner: root
    group: jump
  become: True
